server:
  hostname: 'API_HOSTNAME'
  port: 'PORT'
  adminPort: 'ADMIN_PORT'

authentication:
  username: 'USER'
  password: 'PASSWD'

aws:
  accessKeyId: 'ACCESS_KEY_ID'
  secretAccessKey: 'SECRET_ACCESS_KEY'

api:
  awsBucket: 'AWS_BUCKET'
  dbDirectoryPath: 'DB_PATH'
