server:
  hostname: 'API_HOSTNAME'
  port: 'PORT'
  adminPort: 'ADMIN_PORT'

authentication:
  username: 'USER'
  password: 'PASSWD'

dataSources:
  awsS3:
    bucket: 'S3_BUCKET'
    accessKeyId: 'ACCESS_KEY_ID'
    secretAccessKey: 'SECRET_ACCESS_KEY'
