server:
  hostname: 'API_HOSTNAME'
  port: 'API_PORT'
  adminPort: 'API_ADMIN_PORT'

authentication:
  username: 'API_USER'
  password: 'API_PASSWD'

aws:
  accessKeyId: 'ACCESS_KEY_ID'
  secretAccessKey: 'SECRET_ACCESS_KEY'

api:
  awsBucket: 'AWS_BUCKET'
  dbDirectoryPath: 'DB_PATH'
